### ISSUE TITLE
Missing DLL Files

### ISSUE THREAD

**Issue by MicroSRB2** [Nova-69/Ripping-Tools-GUI#1]
For some odd reason, It keeps asking for DLL files like MSVCP100 and MSVCR100. it never converts the model and its driving me batty. Please help. I have VC Redist 2010 on my pc and that was a bust. I also have the DLL files but the program never calls to use them and just keeps giving me the error

**Comment by Nova-69** [comment]
make sure you've got the net framework redistributable https://learn.microsoft.com/en-us/dotnet/framework/install/guide-for-developers

**Comment by MicroSRB2** [comment]
The newest one?

**Comment by MicroSRB2** [comment]
got it to work. Thanks for the help.
